### ISSUE TITLE
Caja crashes

### ISSUE THREAD

**Issue by palemooner** [mate-desktop/caja#1318]
===================================================================
 Info                                                              
===================================================================
           PID: 2026 (caja)
           UID: 1000 (mint)
           GID: 1000 (mint)
        Signal: 6 (ABRT)
     Timestamp: Tue 2019-11-12 02:19:22 CET (19h ago)
  Command Line: caja
    Executable: /usr/bin/caja
 Control Group: /user.slice/user-1000.slice/session-c1.scope
          Unit: session-c1.scope
         Slice: user-1000.slice
       Session: c1
     Owner UID: 1000 (mint)
       Boot ID: 3186837eaa65410da2d936ee54246f9d
    Machine ID: 16fa2990e5014c52bbca62e8a9eb3558
      Hostname: mint-HP-Pav-15-cs0xxx
       Storage: /var/lib/systemd/coredump/core.caja.1000.3186837eaa65410da2d936ee54246f9d.2026.1573521562000000.lz4
       Message: Process 2026 (caja) of user 1000 dumped core.
                
                Stack trace of thread 2026:
                #0  0x00007fcf3c1fee97 __GI_raise (libc.so.6)
                #1  0x00007fcf3c200801 __GI_abort (libc.so.6)
                #2  0x00007fcf3d949335 g_assertion_message (libglib-2.0.so.0)
                #3  0x00007fcf3d94939a g_assertion_message_expr (libglib-2.0.so.0)
                #4  0x0000560729b64ce9 n/a (caja)
                #5  0x00007fcf3dbfd10d g_closure_invoke (libgobject-2.0.so.0)
                #6  0x00007fcf3dc1005e n/a (libgobject-2.0.so.0)
                #7  0x00007fcf3dc18715 g_signal_emit_valist (libgobject-2.0.so.0)
                #8  0x00007fcf3dc1912f g_signal_emit (libgobject-2.0.so.0)
                #9  0x00007fcf3df51f72 n/a (libgio-2.0.so.0)
                #10 0x00007fcf37314dae ffi_call_unix64 (libffi.so.6)
                #11 0x00007fcf3731471f ffi_call (libffi.so.6)
                #12 0x00007fcf3dbfdced g_cclosure_marshal_generic_va (libgobject-2.0.so.0)
                #13 0x00007fcf3dbfd346 n/a (libgobject-2.0.so.0)
                #14 0x00007fcf3dc183cd g_signal_emit_valist (libgobject-2.0.so.0)
                #15 0x00007fcf3dc1912f g_signal_emit (libgobject-2.0.so.0)
                #16 0x00007fcf3df52748 n/a (libgio-2.0.so.0)
                #17 0x00007fcf3df4d0af n/a (libgio-2.0.so.0)
                #18 0x00007fcf3d922285 g_main_context_dispatch (libglib-2.0.so.0)
                #19 0x00007fcf3d922650 n/a (libglib-2.0.so.0)
                #20 0x00007fcf3d9226dc g_main_context_iteration (libglib-2.0.so.0)
                #21 0x00007fcf3dee3e3d g_application_run (libgio-2.0.so.0)
                #22 0x0000560729b0a290 main (caja)
                #23 0x00007fcf3c1e1b97 __libc_start_main (libc.so.6)
                #24 0x0000560729b0a30a _start (caja)
                
                Stack trace of thread 2167:
                #0  0x00007fcf3c5c2c60 __GI___nanosleep (libpthread.so.0)
                #1  0x00007fcf3d94b86f g_usleep (libglib-2.0.so.0)
                #2  0x00007fcf235e71c5 n/a (libcaja-dropbox.so)
                #3  0x00007fcf3d94a195 n/a (libglib-2.0.so.0)
                #4  0x00007fcf3c5b86db start_thread (libpthread.so.0)
                #5  0x00007fcf3c2e188f __clone (libc.so.6)
                
                Stack trace of thread 2126:
                #0  0x00007fcf3d910a52 g_hash_table_lookup (libglib-2.0.so.0)
                #1  0x00007fcf3df2a411 g_file_monitor_source_handle_event (libgio-2.0.so.0)
                #2  0x00007fcf3df5711e n/a (libgio-2.0.so.0)
                #3  0x00007fcf3df564f9 n/a (libgio-2.0.so.0)
                #4  0x00007fcf3df5673e n/a (libgio-2.0.so.0)
                #5  0x00007fcf3df55a4a n/a (libgio-2.0.so.0)
                #6  0x00007fcf3d922285 g_main_context_dispatch (libglib-2.0.so.0)
                #7  0x00007fcf3d922650 n/a (libglib-2.0.so.0)
                #8  0x00007fcf3d9226dc g_main_context_iteration (libglib-2.0.so.0)
                #9  0x00007fcf3d922721 n/a (libglib-2.0.so.0)
                #10 0x00007fcf3d94a195 n/a (libglib-2.0.so.0)
                #11 0x00007fcf3c5b86db start_thread (libpthread.so.0)
                #12 0x00007fcf3c2e188f __clone (libc.so.6)
                
                Stack trace of thread 2160:
                #0  0x00007fcf3c2d4bf9 __GI___poll (libc.so.6)
                #1  0x00007fcf3d9225c9 n/a (libglib-2.0.so.0)
                #2  0x00007fcf3d9226dc g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007fcf30bf936d n/a (libdconfsettings.so)
                #4  0x00007fcf3d94a195 n/a (libglib-2.0.so.0)
                #5  0x00007fcf3c5b86db start_thread (libpthread.so.0)
                #6  0x00007fcf3c2e188f __clone (libc.so.6)
                
                Stack trace of thread 12172:
                #0  0x00007fcf3c2db839 syscall (libc.so.6)
                #1  0x00007fcf3d96889a g_cond_wait_until (libglib-2.0.so.0)
                #2  0x00007fcf3d8f5571 n/a (libglib-2.0.so.0)
                #3  0x00007fcf3d94ab34 n/a (libglib-2.0.so.0)
                #4  0x00007fcf3d94a195 n/a (libglib-2.0.so.0)
                #5  0x00007fcf3c5b86db start_thread (libpthread.so.0)
                #6  0x00007fcf3c2e188f __clone (libc.so.6)
                
                Stack trace of thread 12171:
                #0  0x00007fcf3c2db839 syscall (libc.so.6)
                #1  0x00007fcf3d96889a g_cond_wait_until (libglib-2.0.so.0)
                #2  0x00007fcf3d8f5571 n/a (libglib-2.0.so.0)
                #3  0x00007fcf3d94ab34 n/a (libglib-2.0.so.0)
                #4  0x00007fcf3d94a195 n/a (libglib-2.0.so.0)
                #5  0x00007fcf3c5b86db start_thread (libpthread.so.0)
                #6  0x00007fcf3c2e188f __clone (libc.so.6)
                
                Stack trace of thread 12173:
                #0  0x00007fcf3c2db839 syscall (libc.so.6)
                #1  0x00007fcf3d96889a g_cond_wait_until (libglib-2.0.so.0)
                #2  0x00007fcf3d8f5571 n/a (libglib-2.0.so.0)
                #3  0x00007fcf3d94ab34 n/a (libglib-2.0.so.0)
                #4  0x00007fcf3d94a195 n/a (libglib-2.0.so.0)
                #5  0x00007fcf3c5b86db start_thread (libpthread.so.0)
                #6  0x00007fcf3c2e188f __clone (libc.so.6)
                
                Stack trace of thread 2131:
                #0  0x00007fcf3c2d4bf9 __GI___poll (libc.so.6)
                #1  0x00007fcf3d9225c9 n/a (libglib-2.0.so.0)
                #2  0x00007fcf3d922962 g_main_loop_run (libglib-2.0.so.0)
                #3  0x00007fcf3df100e6 n/a (libgio-2.0.so.0)
                #4  0x00007fcf3d94a195 n/a (libglib-2.0.so.0)
                #5  0x00007fcf3c5b86db start_thread (libpthread.so.0)
                #6  0x00007fcf3c2e188f __clone (libc.so.6)
===================================================================
 GDB Log                                                           
===================================================================
[New LWP 2026]
[New LWP 2167]
[New LWP 2126]
[New LWP 2160]
[New LWP 12172]
[New LWP 12171]
[New LWP 12173]
[New LWP 2131]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `caja'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7fcf40dd1000 (LWP 2026))]

===================================================================
 GDB Backtrace                                                     
===================================================================
[New LWP 2026]
[New LWP 2167]
[New LWP 2126]
[New LWP 2160]
[New LWP 12172]
[New LWP 12171]
[New LWP 12173]
[New LWP 2131]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `caja'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7fcf40dd1000 (LWP 2026))]
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007fcf3c200801 in __GI_abort () at abort.c:79
#2  0x00007fcf3d949335 in g_assertion_message () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fcf3d94939a in g_assertion_message_expr () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x0000560729b64ce9 in ?? ()
#5  0x00007fcf3dbfd10d in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007fcf3dc1005e in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007fcf3dc18715 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007fcf3dc1912f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#9  0x00007fcf3df51f72 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#10 0x00007fcf37314dae in ffi_call_unix64 () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#11 0x00007fcf3731471f in ffi_call () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#12 0x00007fcf3dbfdced in g_cclosure_marshal_generic_va () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007fcf3dbfd346 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#14 0x00007fcf3dc183cd in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#15 0x00007fcf3dc1912f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#16 0x00007fcf3df52748 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#17 0x00007fcf3df4d0af in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#18 0x00007fcf3d922285 in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007fcf3d922650 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007fcf3d9226dc in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#21 0x00007fcf3dee3e3d in g_application_run () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#22 0x0000560729b0a290 in main ()

===================================================================
 GDB Backtrace (all threads)                                       
===================================================================
[New LWP 2026]
[New LWP 2167]
[New LWP 2126]
[New LWP 2160]
[New LWP 12172]
[New LWP 12171]
[New LWP 12173]
[New LWP 2131]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `caja'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7fcf40dd1000 (LWP 2026))]

Thread 8 (Thread 0x7fcf32271700 (LWP 2131)):
#0  0x00007fcf3c2d4bf9 in __GI___poll (fds=0x7fcf24042fd0, nfds=4, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007fcf3d9225c9 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007fcf3d922962 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007fcf3df100e6 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#4  0x00007fcf3d94a195 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007fcf3c5b86db in start_thread (arg=0x7fcf32271700) at pthread_create.c:463
        pd = 0x7fcf32271700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140527876380416, 1060002612567795031, 140527876377728, 0, 94588773948496, 140732228285680, -1068612548156791465, -1068590657082038953}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#6  0x00007fcf3c2e188f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 7 (Thread 0x7fcf16993700 (LWP 12173)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
No locals.
#1  0x00007fcf3d96889a in g_cond_wait_until () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007fcf3d8f5571 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007fcf3d94ab34 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007fcf3d94a195 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007fcf3c5b86db in start_thread (arg=0x7fcf16993700) at pthread_create.c:463
        pd = 0x7fcf16993700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140527414097664, 1060002612567795031, 140527414094976, 0, 140526766526080, 140732228283664, -1068531853237492393, -1068590657082038953}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#6  0x00007fcf3c2e188f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 6 (Thread 0x7fcf179c4700 (LWP 12171)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
No locals.
#1  0x00007fcf3d96889a in g_cond_wait_until () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007fcf3d8f5571 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007fcf3d94ab34 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007fcf3d94a195 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007fcf3c5b86db in start_thread (arg=0x7fcf179c4700) at pthread_create.c:463
        pd = 0x7fcf179c4700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140527431075584, 1060002612567795031, 140527431072896, 0, 94588788320496, 140732228286224, -1068534008774204073, -1068590657082038953}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#6  0x00007fcf3c2e188f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 5 (Thread 0x7fcf16192700 (LWP 12172)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
No locals.
#1  0x00007fcf3d96889a in g_cond_wait_until () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007fcf3d8f5571 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007fcf3d94ab34 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007fcf3d94a195 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007fcf3c5b86db in start_thread (arg=0x7fcf16192700) at pthread_create.c:463
        pd = 0x7fcf16192700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140527405704960, 1060002612567795031, 140527405702272, 0, 140526766550176, 140732228283664, -1068532953285991081, -1068590657082038953}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#6  0x00007fcf3c2e188f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 4 (Thread 0x7fcf30bf1700 (LWP 2160)):
#0  0x00007fcf3c2d4bf9 in __GI___poll (fds=0x56072a4e1480, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007fcf3d9225c9 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007fcf3d9226dc in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007fcf30bf936d in ?? () from /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
No symbol table info available.
#4  0x00007fcf3d94a195 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007fcf3c5b86db in start_thread (arg=0x7fcf30bf1700) at pthread_create.c:463
        pd = 0x7fcf30bf1700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140527852787456, 1060002612567795031, 140527852784768, 0, 94588774417648, 140732228283648, -1068615640533244585, -1068590657082038953}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#6  0x00007fcf3c2e188f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 3 (Thread 0x7fcf32a72700 (LWP 2126)):
#0  0x00007fcf3d910a52 in g_hash_table_lookup () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#1  0x00007fcf3df2a411 in g_file_monitor_source_handle_event () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#2  0x00007fcf3df5711e in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#3  0x00007fcf3df564f9 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#4  0x00007fcf3df5673e in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#5  0x00007fcf3df55a4a in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#6  0x00007fcf3d922285 in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#7  0x00007fcf3d922650 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#8  0x00007fcf3d9226dc in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#9  0x00007fcf3d922721 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#10 0x00007fcf3d94a195 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#11 0x00007fcf3c5b86db in start_thread (arg=0x7fcf32a72700) at pthread_create.c:463
        pd = 0x7fcf32a72700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140527884773120, 1060002612567795031, 140527884770432, 0, 94588773720944, 140732228285296, -1068611448108292777, -1068590657082038953}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#12 0x00007fcf3c2e188f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 2 (Thread 0x7fcf235e0700 (LWP 2167)):
#0  0x00007fcf3c5c2c60 in __GI___nanosleep (requested_time=0x7fcf235df9c0, remaining=0x7fcf235df9d0) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007fcf3d94b86f in g_usleep () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007fcf235e71c5 in ?? () from /usr/lib/x86_64-linux-gnu/caja/extensions-2.0/libcaja-dropbox.so
No symbol table info available.
#3  0x00007fcf3d94a195 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007fcf3c5b86db in start_thread (arg=0x7fcf235e0700) at pthread_create.c:463
        pd = 0x7fcf235e0700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140527628322560, 1060002612567795031, 140527628319872, 0, 94588774912480, 140732228283840, -1068579644949207721, -1068590657082038953}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#5  0x00007fcf3c2e188f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 1 (Thread 0x7fcf40dd1000 (LWP 2026)):
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
        set = {__val = {0, 94588790713496, 94588790713692, 94588790713392, 94588790713692, 0, 2064, 124, 94588765377877, 140732228283872, 140528047537216, 140528044034008, 567971610624, 2048, 344306352128, 7}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007fcf3c200801 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x3d974ff9, sa_sigaction = 0x3d974ff9}, sa_mask = {__val = {94588783661424, 0, 140732228283872, 140728898420737, 2081775603759911936, 72057594037927936, 16777216, 7205759403792793600, 94590145134592, 94588783661424, 0, 0, 2081775603759911936, 94588765377877, 94588783661424, 101}}, sa_flags = 1035910624, sa_restorer = 0x7ffec679ade0}
        sigs = {__val = {32, 0 <repeats 15 times>}}
        __cnt = <optimized out>
        __set = <optimized out>
        __cnt = <optimized out>
        __set = <optimized out>
#2  0x00007fcf3d949335 in g_assertion_message () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007fcf3d94939a in g_assertion_message_expr () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x0000560729b64ce9 in ?? ()
No symbol table info available.
#5  0x00007fcf3dbfd10d in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#6  0x00007fcf3dc1005e in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#7  0x00007fcf3dc18715 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#8  0x00007fcf3dc1912f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#9  0x00007fcf3df51f72 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#10 0x00007fcf37314dae in ffi_call_unix64 () from /usr/lib/x86_64-linux-gnu/libffi.so.6
No symbol table info available.
#11 0x00007fcf3731471f in ffi_call () from /usr/lib/x86_64-linux-gnu/libffi.so.6
No symbol table info available.
#12 0x00007fcf3dbfdced in g_cclosure_marshal_generic_va () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#13 0x00007fcf3dbfd346 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#14 0x00007fcf3dc183cd in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#15 0x00007fcf3dc1912f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#16 0x00007fcf3df52748 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#17 0x00007fcf3df4d0af in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#18 0x00007fcf3d922285 in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#19 0x00007fcf3d922650 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#20 0x00007fcf3d9226dc in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#21 0x00007fcf3dee3e3d in g_application_run () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#22 0x0000560729b0a290 in main ()
No symbol table info available.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007fcf3c200801 in __GI_abort () at abort.c:79
#2  0x00007fcf3d949335 in g_assertion_message () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fcf3d94939a in g_assertion_message_expr () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x0000560729b64ce9 in ?? ()
#5  0x00007fcf3dbfd10d in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007fcf3dc1005e in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007fcf3dc18715 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007fcf3dc1912f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#9  0x00007fcf3df51f72 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#10 0x00007fcf37314dae in ffi_call_unix64 () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#11 0x00007fcf3731471f in ffi_call () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#12 0x00007fcf3dbfdced in g_cclosure_marshal_generic_va () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007fcf3dbfd346 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#14 0x00007fcf3dc183cd in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#15 0x00007fcf3dc1912f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#16 0x00007fcf3df52748 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#17 0x00007fcf3df4d0af in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#18 0x00007fcf3d922285 in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007fcf3d922650 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007fcf3d9226dc in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#21 0x00007fcf3dee3e3d in g_application_run () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#22 0x0000560729b0a290 in main ()

**Comment by lukefromdc** [comment]
This sure looks like you have a missing file in your OS installation. The lines that show this are

```
Program terminated with signal SIGABRT, Aborted.
#0 __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51 ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
```
