### ISSUE TITLE
1.27.0: test suite is failing

### ISSUE THREAD

**Issue by kloczek** [mate-desktop/caja#1693]
#### Expected behaviour
Test suite should nit fail

#### Actual behaviour
<details>

```console
+ cd caja-1.27.0
+ xvfb-run -a /usr/bin/make -O -j48 V=1 VERBOSE=1 check
Making check in po
make[1]: Nothing to be done for 'check'.
Making check in eel
/usr/bin/make  check-am
/usr/bin/make  check-TESTS
make[4]: Entering directory '/home/tkloczko/rpmbuild/BUILD/caja-1.27.0/eel'
PASS: check-eel
make[4]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/caja-1.27.0/eel'
make[4]: Entering directory '/home/tkloczko/rpmbuild/BUILD/caja-1.27.0/eel'
============================================================================
Testsuite summary for caja 1.27.0
============================================================================
# TOTAL: 1
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
make[4]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/caja-1.27.0/eel'
Making check in libcaja-extension
make[1]: Nothing to be done for 'check'.
Making check in mate-submodules
Making check in libegg
make[2]: Nothing to be done for 'check'.
make[2]: Nothing to be done for 'check-am'.
Making check in libcaja-private
/usr/bin/make  check-am
make[2]: Nothing to be done for 'check-am'.
Making check in src
/usr/bin/make  check-recursive
Making check in file-manager
/usr/bin/make  check-am
make[4]: Nothing to be done for 'check-am'.
make[3]: Entering directory '/home/tkloczko/rpmbuild/BUILD/caja-1.27.0/src'
true -P ./ -f ./ui-a11y.false -s ./ui-a11y.suppr -o ui-a11y.err
make[3]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/caja-1.27.0/src'
/usr/bin/make  check-TESTS
make[5]: Entering directory '/home/tkloczko/rpmbuild/BUILD/caja-1.27.0/src'
FAIL: check-caja
make[5]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/caja-1.27.0/src'
make[5]: Entering directory '/home/tkloczko/rpmbuild/BUILD/caja-1.27.0/src'
=====================================
   caja 1.27.0: src/test-suite.log
=====================================

# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: check-caja
================

running caja_self_check_file_utilities
running caja_self_check_file_operations
running caja_self_check_directory

(caja:4181472): GLib-GIO-ERROR **: 13:32:20.023: Settings schema 'org.mate.caja.preferences' is not installed
./check-caja: line 2: 4181472 Trace/breakpoint trap   (core dumped) ./caja --check --g-fatal-warnings
FAIL check-caja (exit status: 133)

============================================================================
Testsuite summary for caja 1.27.0
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See src/test-suite.log
Please report to https://github.com/mate-desktop/caja/issues
============================================================================
```
</details>

Core call trace
</details>

```console
[tkloczko@barrel SRPMS]$ echo "bt full" | coredumpctl gdb 1322690
           PID: 1322690 (caja)
           UID: 1000 (tkloczko)
           GID: 1000 (tkloczko)
        Signal: 5 (TRAP)
     Timestamp: Thu 2023-01-26 13:32:20 GMT (3h 16min ago)
  Command Line: /home/tkloczko/rpmbuild/BUILD/caja-1.27.0/src/.libs/caja --check --g-fatal-warnings
    Executable: /home/tkloczko/rpmbuild/BUILD/caja-1.27.0/src/.libs/caja
 Control Group: /lxc.payload.pers-jacek/user.slice/user-1000.slice/session-26.scope
         Slice: -.slice
       Boot ID: 10c9b88141d540f798b83a68ec072478
    Machine ID: 1e3406b3ce714f53abecf7641173d045
      Hostname: pers-jacek
       Storage: /var/lib/systemd/coredump/core.caja.1000.10c9b88141d540f798b83a68ec072478.1322690.1674739940000000.zst (present)
     Disk Size: 1.8M
       Message: Process 1322690 (caja) of user 1000 dumped core.

                Module /home/tkloczko/rpmbuild/BUILD/caja-1.27.0/src/.libs/caja with build-id 6bf47ce750725fb717ad925fdf70e4132b1d9dc1
                Module /usr/lib64/gvfs/libgvfscommon.so with build-id a9c2990e0681323824a1e1f14b9006978f271cd9
                Module /usr/lib64/gio/modules/libgvfsdbus.so with build-id fca7908a987a632b0dd2e7732b1e98c35fc1f73d
                Module /usr/lib64/libtinfo.so.6.2.0 with build-id 68dfa948f2e810ee458b5b6f1d54a90389c0086a
                Module /usr/lib64/libdrm_nouveau.so.2.0.0 with build-id f10a5c9d202a1e0036ac007e40158d10ad40306d
                Module /usr/lib64/libdrm_amdgpu.so.1.0.0 with build-id 202b2040c34fc80510f68f33da2689e023f1404a
                Module /usr/lib64/libelf-0.187.so with build-id a85f3238a42cb0f955875ed6ea223b75676a45ea
                Module /usr/lib64/libdrm_radeon.so.1.0.1 with build-id c61c92d37d24860684f3679510858cd523bb21e8
                Module /usr/lib64/libLLVM-15.so.0 with build-id 6af8482ffcec745422c407cfb8f1eaa602a17c22
                Module /usr/lib64/dri/swrast_dri.so with build-id d629bd2884bfd3eedbe93dc96e05b08cc44499ab
                Module /usr/lib64/libxshmfence.so.1.0.0 with build-id b3ebebfa9ce1d37b711123f68885b000c97b03cf
                Module /usr/lib64/libXxf86vm.so.1.0.0 with build-id 2cf04924bc737fe16c7d76348ca4c1989bdb45a2
                Module /usr/lib64/libdrm.so.2.4.0 with build-id f0a7afef2034341ce5779e8e365bb5a7167cb605
                Module /usr/lib64/libglapi.so.0.0.0 with build-id 557bc2aaa41e3bf929abc3f7ba3c6dd91ba6fafd
                Module /usr/lib64/libGLX_mesa.so.0.0.0 with build-id a58d4d5d34d1f076ec312fb29f23427c9de9ca22
                Module /usr/lib64/libicudata.so.72.1 with build-id 0ecb549c46094c3b653b1fc36a8e14d41b3ed510
                Module /usr/lib64/libsystemd.so.0.34.0 with build-id b5394eb4314dab6e18e2afd7883ef612fda9d88e
                Module /usr/lib64/libjson-glib-1.0.so.0.600.6 with build-id ff92b16a4625a9dec876a23d3cd8d2c231173bc2
                Module /usr/lib64/libicui18n.so.72.1 with build-id 5b1a3a423c39d928b691c3eb7e9268fd1550b30a
                Module /usr/lib64/libicuuc.so.72.1 with build-id 26c54285601e94fcc29e8619f7805435eec325b5
                Module /usr/lib64/libdbus-1.so.3.32.1 with build-id e65b6716234770b6639cf427769294048333d0a6
                Module /usr/lib64/libatspi.so.0.0.1 with build-id f1bd52917cc23e779032d2195bd9726093660bcf
                Module /usr/lib64/libblkid.so.1.1.0 with build-id 386b01e2a998077292f5d496440c9422cd55c834
                Module /usr/lib64/libbz2.so.1.0.6 with build-id 023dc739b5fd30a2fc0282b7529a7689579f7477
                Module /usr/lib64/libXau.so.6.0.0 with build-id fbd93a8705586186a224d93820461095cc3d2c51
                Module /usr/lib64/libX11-xcb.so.1.0.0 with build-id 81315cba976bf19ffbf9959e7a25c11010958560
                Module /usr/lib64/libxcb-util.so.1.0.0 with build-id 2ed3995cac8c7b9771d70b32f0a87565838566c6
                Module /usr/lib64/libgcc_s-13-20230117.so.1 with build-id 235a32d310cd394912dcf8a82bcad162a8ee88de
                Module /usr/lib64/libstdc++.so.6.0.31 with build-id c949e8b5e1107845d4cd0429fc458b739ee80a29
                Module /usr/lib64/libexpat.so.1.8.10 with build-id c51b3f7b04e8643ed85077b8b1e95e3a8313f75a
                Module /usr/lib64/libtracker-sparql-3.0.so.0.500.0 with build-id 28a3bd80f065b91dbce67cfccf0e8d71a9d8fb96
                Module /usr/lib64/libcloudproviders.so.0.3.1 with build-id 1e0c6122bfdf775ba73608beb29471e3421d63ba
                Module /usr/lib64/libatk-bridge-2.0.so.0.0.0 with build-id 98c30eddc1fcf5a0efd98dcbec0c0f7976708a13
                Module /usr/lib64/libmount.so.1.1.0 with build-id 8b27df236888bb335bed23c89d56e0659c409044
                Module /usr/lib64/libXrender.so.1.3.0 with build-id 97facdaf47a4decc8a32fd45fcc2768ef907e1b2
                Module /usr/lib64/libfreetype.so.6.18.3 with build-id 059fc9b092f63f98ee9ae821bca24b3fcdc0d9e1
                Module /usr/lib64/libpangoft2-1.0.so.0.5000.12 with build-id 81182f07f8af3fb4db2789f7fc842d5eb6aac9be
                Module /usr/lib64/libthai.so.0.3.1 with build-id 26aa8690cda12324faf29ddb858f2e04a08ad09d
                Module /usr/lib64/libXinerama.so.1.0.0 with build-id 4e750346066532f6a3f93d7fc7a0ea1cb9fd2b06
                Module /usr/lib64/libXcomposite.so.1.0.0 with build-id c5370b61a735a138b52d4cadfab6fd31bba3646e
                Module /usr/lib64/libXdamage.so.1.1.0 with build-id fa8d16ee8806fb81db5625773186a5e3ad25fde2
                Module /usr/lib64/libXcursor.so.1.0.2 with build-id 8eca5197993fc5225bab0fe09a81b51b1af1edf3
                Module /usr/lib64/libXfixes.so.3.1.0 with build-id 834b787b4973a7e00e92892b4bd237f7f256bb74
                Module /usr/lib64/libXext.so.6.4.0 with build-id 66eea3540673f46a280e75f3ef11633871094a7f
                Module /usr/lib64/libXi.so.6.1.0 with build-id 4186d37b64ea97664682cc0c51284d91554369a9
                Module /usr/lib64/libwayland-egl.so.1.21.0 with build-id 12847ae55db4cd2e09099f6d1cb748b9a4318d50
                Module /usr/lib64/libwayland-cursor.so.0.21.0 with build-id 4270fc1189cdb3c3fc56818715130df08d2c4692
                Module /usr/lib64/libwayland-client.so.0.21.0 with build-id 185c3216aaa4c5c7d2d307a7836d663414e84e76
                Module /usr/lib64/libxkbcommon.so.0.0.0 with build-id 851472cee9167641f0ccf2ed0c4b842488ba2051
                Module /usr/lib64/libfontconfig.so.1.12.0 with build-id 9d8589a0259255cbe11260dda9f5c2034f4ef25b
                Module /usr/lib64/libepoxy.so.0.0.0 with build-id 2eddde4d01350cf3c3729e4c366de2124e909b46
                Module /usr/lib64/libfribidi.so.0.4.0 with build-id 58761dc040956ed14a0aab59631c2a29a750dd66
                Module /usr/lib64/libdconf.so.1.0.0 with build-id 45f04adfbaf6561068e4f44bfdc2003716e0cca7
                Module /usr/lib64/libstartup-notification-1.so.0.0.0 with build-id b9169463bd2a2d3751aaaeb0ceee5d5ba6b1f247
                Module /usr/lib64/libXrandr.so.2.2.0 with build-id 26318f0b43f0893b873d4228055f1075d4f54fcc
                Module /usr/lib64/libuuid.so.1.3.0 with build-id 4ab81ea110896ea5a42a910f26cff8dac3395e5a
                Module /usr/lib64/libselinux.so.1 with build-id 227eb1b34fe69134c80d7c5c54df6b254f60df3d
                Module /usr/lib64/libnotify.so.4.0.0 with build-id 2c73114cd9c1b6e38efbeffb72dae797772e3950
                Module /usr/lib64/libexempi.so.8.1.3 with build-id 250edfd16078525b81b4091e37b4d6f4397dc60b
                Module /usr/lib64/libexif.so.12.3.4 with build-id 7a9ad9fd9a9d62503f23cf119b4e197c5f43ee91
                Module /usr/lib64/libgtk-3.so.0.2404.32 with build-id 586025707eedb3b942b3121b244a57c21aa4e85b
                Module /usr/lib64/libatk-1.0.so.0.24710.1 with build-id b854e2384ab1d8f21438736f5cf3afd01b1e1016
                Module /usr/lib64/libcairo-gobject.so.2.11706.0 with build-id 1dc7ea6e38db83fd7102853d330230eb1b4f035b
                Module /usr/lib64/libgdk_pixbuf-2.0.so.0.4200.10 with build-id ca7f2549f4a6e7d31dd3326e43538f03c07d99ec
                Module /usr/lib64/libcairo.so.2.11706.0 with build-id c10cb485cb9e8bc9ede2759d9cd85dff2a1b5d59
                Module /usr/lib64/libpangocairo-1.0.so.0.5000.12 with build-id db2d543b5a3db7f4c29ece165447711c434fe76c
                Module /usr/lib64/libpango-1.0.so.0.5000.12 with build-id c49ad348b5c214420cd035a7ed99c011d72ed289
                Module /usr/lib64/libgdk-3.so.0.2404.32 with build-id d953f54f2834b078fe9847828afcc5e98c892a91
                Module /usr/lib64/libX11.so.6.4.0 with build-id 6b26f2d9923da219f0b53e947a2ab39b6dd86bca
                Module /usr/lib64/libxml2.so.2.10.3 with build-id 5f1c79505104892f6ae91b32ed167dd7de81e9df
                Module /usr/lib64/libgailutil-3.so.0.0.0 with build-id 482db70e4be514e518d8ab3b32f85c94f02c85df
                Module /usr/lib64/libmate-desktop-2.so.17.1.4 with build-id 3fef74f792b8afcb0f8b4911f1f3f2c79c691980
                Module /home/tkloczko/rpmbuild/BUILD/caja-1.27.0/libcaja-extension/.libs/libcaja-extension.so.1.4.0 with build-id fdd80c884e4748c8ae126f897223284cf2e62ae1
                Module /usr/lib64/libICE.so.6.3.0 with build-id 8f96189cdeed2b6ae844bec25f81cf0c96b475a8
                Module /usr/lib64/libSM.so.6.0.1 with build-id ddcab9596d778b8221a3389fef096038bd13ebb9
                Module linux-vdso.so.1 with build-id c26808872d57ea78c1437acf55d97b0d9840149f
                Module libedit.so.0 with build-id b3c5dd3cbf8398cb9dc4b7091d5d83500b20bdb1
                Module libxcb-xfixes.so.0 with build-id da19ece3d77977560f1b03de9e253dcef15ddc74
                Module libxcb-sync.so.1 with build-id e7297d4e8b6b3655847a413d43cdc63ed2fff281
                Module libxcb-present.so.0 with build-id cf8c5aec0c7c355196620f58d9a308838f0830cc
                Module libxcb-dri3.so.0 with build-id 342dd2d2b138a7296e41ba13a669bef8859c54d2
                Module libxcb-dri2.so.0 with build-id 3b151cde2e69273882f64dd8d6075fa44602109d
                Module libxcb-glx.so.0 with build-id 89e53c0bcb1adc8124e54263ace30f214ed95a60
                Module libgpg-error.so.0 with build-id bf47931d1bcfd1bc2454bf1ce6759a89a124c4c5
                Module liblz4.so.1 with build-id cd98594a2d4af514cd25f09454311482254c0700
                Module libzstd.so.1 with build-id 6110212e30147b96011040788a7a719c63eb9e43
                Module libgcrypt.so.20 with build-id 8ef1fdcc4d29532c4cad59aa4cbb750e95788dd3
                Module libcap.so.2 with build-id 0ccbda49aa2837f249cbed5af208cb5c670fd935
                Module libsqlite3.so.0 with build-id d2eeff453fd5ab80a55ee8a7bf21178ded0385d5
                Module libGLdispatch.so.0 with build-id 4407ae3b1765191433858f3991c4a30842d03d30
                Module libGLX.so.0 with build-id 5ad4dcd86d4fde2543a733b1f4549299ff43805b
                Module libgraphite2.so.3 with build-id f4c12746303e8595f292632435603e0e9eb3893e
                Module libdatrie.so.1 with build-id e58e6110dafc4fa0077eae5d0c71572c848b077f
                Module ld-linux-x86-64.so.2 with build-id 17fe11adf8b2b7e4ec9cd8dd169945ac298110c7
                Module libpixman-1.so.0 with build-id fadd77f2401dc3e893ab37997b8a45f1b837a605
                Module libEGL.so.1 with build-id ce5d4ce38c2d14a787e7c2ab37f0c5465bee63bf
                Module libGL.so.1 with build-id d762156f36a83e0015e881fba50479fe9d71d3c8
                Module libxcb-shm.so.0 with build-id d8dc61e42b659c671cedbd4f856294191eec712c
                Module libxcb-render.so.0 with build-id 0331c246668189aed658a300895498e233179ada
                Module libpng16.so.16 with build-id 1e0a7f6ae474734329a2af02d355f467c45ceb4b
                Module libpcre2-8.so.0 with build-id b9f4c75fc307b1cf4aa99f90f00e469283f4e1ce
                Module libffi.so.8 with build-id db49d1e7a7fee2853378f3b4156f7da5ea53fc5a
                Module libharfbuzz.so.0 with build-id f6c910ee21f0a17f65299c924f8e126e4a74f09b
                Module libxcb.so.1 with build-id 8c79af8b6d9bc502d668d6911001ce01dbbf839a
                Module liblzma.so.5 with build-id 6f488e00a3fe6413de6d2ae209ec0afe4cc2a3e5
                Module libz.so.1 with build-id 0f4fc230c448d0e0fb5fe421e30d3dae0cdac53c
                Module libc.so.6 with build-id 282757a907fbf794bc8dbf9514ad3259af77ade6
                Module libm.so.6 with build-id 00ed683a998af98f4f13854aefbfda52db223ddc
                Module libgio-2.0.so.0 with build-id a05c68caf1d8c0d56fbbae0176a83cddea86644f
                Module libglib-2.0.so.0 with build-id 642bec9c053455e95aa706a2d46a5e346574b1f0
                Module libgobject-2.0.so.0 with build-id fd27dc0ae831c601151aea2bb5207d2f7b8fd391
                Module libgmodule-2.0.so.0 with build-id b1cac98ac1050db3984eaac006e511fd458abbbe
                Stack trace of thread 4181472:
                #0  0x00007f719dc85717 g_log_structured_array (libglib-2.0.so.0 + 0x35717)
                #1  0x00007f719dc857f2 g_log_default_handler (libglib-2.0.so.0 + 0x357f2)
                #2  0x00007f719dc8e052 g_logv (libglib-2.0.so.0 + 0x3e052)
                #3  0x00007f719dc8e303 g_log (libglib-2.0.so.0 + 0x3e303)
                #4  0x00007f719da00d40 g_settings_set_property (libgio-2.0.so.0 + 0xd2d40)
                #5  0x00007f719dd9ae7e object_set_property (libgobject-2.0.so.0 + 0x35e7e)
                #6  0x00007f719dd9b798 g_object_new_internal (libgobject-2.0.so.0 + 0x36798)
                #7  0x00007f719dd9c03b g_object_new_valist (libgobject-2.0.so.0 + 0x3703b)
                #8  0x00007f719dd9c67d g_object_new (libgobject-2.0.so.0 + 0x3767d)
                #9  0x0000560574cafde2 n/a (/home/tkloczko/rpmbuild/BUILD/caja-1.27.0/src/.libs/caja + 0x99de2)
                #10 0x0000560574d195be n/a (/home/tkloczko/rpmbuild/BUILD/caja-1.27.0/src/.libs/caja + 0x1035be)
                #11 0x0000560574d1a44f n/a (/home/tkloczko/rpmbuild/BUILD/caja-1.27.0/src/.libs/caja + 0x10444f)
                #12 0x0000560574d1dcd2 n/a (/home/tkloczko/rpmbuild/BUILD/caja-1.27.0/src/.libs/caja + 0x107cd2)
                #13 0x0000560574d1df96 n/a (/home/tkloczko/rpmbuild/BUILD/caja-1.27.0/src/.libs/caja + 0x107f96)
                #14 0x0000560574d25fca n/a (/home/tkloczko/rpmbuild/BUILD/caja-1.27.0/src/.libs/caja + 0x10ffca)
                #15 0x00007f719da3553e g_application_run (libgio-2.0.so.0 + 0x10753e)
                #16 0x0000560574c6f183 n/a (/home/tkloczko/rpmbuild/BUILD/caja-1.27.0/src/.libs/caja + 0x59183)
                #17 0x00007f719ccd0a90 __libc_start_call_main (libc.so.6 + 0x27a90)
                #18 0x00007f719ccd0b49 __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x27b49)
                #19 0x0000560574c6f1e5 n/a (/home/tkloczko/rpmbuild/BUILD/caja-1.27.0/src/.libs/caja + 0x591e5)
                ELF object binary architecture: AMD x86-64

GNU gdb (GDB) Fedora 12.1-4.fc37
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/tkloczko/rpmbuild/BUILD/caja-1.27.0/src/.libs/caja...

[New LWP 4181472]
[New LWP 4181487]
[New LWP 4181486]



Core was generated by `/home/tkloczko/rpmbuild/BUILD/caja-1.27.0/src/.libs/caja --check --g-fatal-warn'.
Program terminated with signal SIGTRAP, Trace/breakpoint trap.
#0  0x00007f719dc85717 in g_log_structured_array () from /usr/lib64/libglib-2.0.so.0
[Current thread is 1 (Thread 0x7f719985ca80 (LWP 4181472))]
Missing separate debuginfos, use: dnf debuginfo-install at-spi2-core-2.47.1-2.fc35.x86_64 atk-2.47.1-2.fc35.x86_64 bzip2-libs-1.0.8-13.fc35.x86_64 cairo-1.17.6-3.fc35.x86_64 dbus-libs-1.14.4-2.fc35.x86_64 elfutils-libelf-0.187-9.fc35.x86_64 expat-2.5.0-2.fc35.x86_64 fontconfig-2.14.1-3.fc35.x86_64 freetype-2.12.1-4.fc35.x86_64 glib2-2.75.2-2.1.fc35.x86_64 glibc-2.36.9000-19.fc38.x86_64 graphite-1.3.14-11.fc35.x86_64 harfbuzz-6.0.0-3.fc35.x86_64 libX11-1.8.3-2.fc35.x86_64 libXau-1.0.11-2.fc35.x86_64 libXext-1.3.5-2.fc35.x86_64 libXrender-0.9.11-2.fc35.x86_64 libblkid-2.38.1-3.fc38.x86_64 libcap-2.66-2.fc35.x86_64 libdatrie-0.2.13-5.fc35.x86_64 libedit-3.1-45.20221030cvs.2.fc35.x86_64 libffi-3.4.4-2.fc35.x86_64 libgcc-12.2.1-4.fc38.x86_64 libgcrypt-1.10.1-7.fc35.x86_64 libglvnd-1.6.0-2.fc35.x86_64 libglvnd-egl-1.6.0-2.fc35.x86_64 libglvnd-glx-1.6.0-2.fc35.x86_64 libgpg-error-1.46-2.fc35.x86_64 libicu-72.1-2.fc35.x86_64 libmount-2.38.1-3.fc38.x86_64 libpng-1.6.39-2.fc35.x86_64 libselinux-3.5-0.rc1.1.fc38.x86_64 libstdc++-12.2.1-4.fc38.x86_64 libxcb-1.15-2.fc35.x86_64 libxml2-2.10.3-3.fc35.x86_64 libzstd-1.5.2-4.fc35.x86_64 lz4-libs-1.9.4-2.fc35.x86_64 ncurses-libs-6.2-9.20210508.fc36.x86_64 pcre2-10.42-2.fc35.x86_64 pixman-0.42.2-2.fc35.x86_64 sqlite-libs-3.40.1-2.fc35.x86_64 systemd-libs-251.4-54.fc35.x86_64 xz-libs-5.4.1-2.fc35.x86_64
(gdb) #0  0x00007f719dc85717 in g_log_structured_array () from /usr/lib64/libglib-2.0.so.0
No symbol table info available.
#1  0x00007f719dc857f2 in g_log_default_handler () from /usr/lib64/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f719dc8e052 in g_logv () from /usr/lib64/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f719dc8e303 in g_log () from /usr/lib64/libglib-2.0.so.0
No symbol table info available.
#4  0x00007f719da00d40 in g_settings_set_property () from /usr/lib64/libgio-2.0.so.0
No symbol table info available.
#5  0x00007f719dd9ae7e in object_set_property () from /usr/lib64/libgobject-2.0.so.0
No symbol table info available.
#6  0x00007f719dd9b798 in g_object_new_internal () from /usr/lib64/libgobject-2.0.so.0
No symbol table info available.
#7  0x00007f719dd9c03b in g_object_new_valist () from /usr/lib64/libgobject-2.0.so.0
No symbol table info available.
#8  0x00007f719dd9c67d in g_object_new () from /usr/lib64/libgobject-2.0.so.0
No symbol table info available.
#9  0x0000560574cafde2 in caja_global_preferences_init () at ../libcaja-private/caja-global-preferences.c:91
        initialized = <optimized out>
#10 caja_global_preferences_init () at ../libcaja-private/caja-global-preferences.c:80
        initialized = 1
#11 0x0000560574d195be in caja_directory_get_internal (location=location@entry=0x5605763dc780, create=create@entry=1) at ../libcaja-private/caja-directory.c:272
        directory = <optimized out>
#12 0x0000560574d1a44f in caja_directory_get_by_uri (uri=uri@entry=0x560574d5fd4f "file:///etc") at ../libcaja-private/caja-directory.c:336
        directory = <optimized out>
        location = 0x5605763dc780
#13 0x0000560574d1dcd2 in caja_self_check_directory () at ../libcaja-private/caja-directory.c:1708
        directory = <optimized out>
        file = <optimized out>
#14 0x0000560574d1df96 in caja_run_lib_self_checks () at ../libcaja-private/caja-lib-self-check-functions.c:35
No locals.
#15 0x0000560574d25fca in do_perform_self_checks (exit_status=0x7fff79a02154) at /home/tkloczko/rpmbuild/BUILD/caja-1.27.0/src/caja-application.c:1830
No locals.
#16 caja_application_local_command_line (application=0x560576294000, arguments=<optimized out>, exit_status=0x7fff79a02154)
    at /home/tkloczko/rpmbuild/BUILD/caja-1.27.0/src/caja-application.c:1995
        perform_self_check = 1
        version = 0
        browser_window = 0
        open_in_tabs = 0
        kill_shell = 0
        autostart_id = 0x0
        no_default_window = 0
        select_uris = 0
        remaining = 0x0
        self = <optimized out>
        options = {{long_name = 0x560574d62390 "check", short_name = 99 'c', flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x7fff79a01e2c,
            description = 0x560574d62396 "Perform a quick set of self-check tests.", arg_description = 0x0}, {long_name = 0x560574d4eb38 "version", short_name = 0 '\000', flags = 0,
            arg = G_OPTION_ARG_NONE, arg_data = 0x7fff79a01e28, description = 0x560574d623bf "Show the version of the program.", arg_description = 0x0}, {
            long_name = 0x560574d57330 "geometry", short_name = 103 'g', flags = 0, arg = G_OPTION_ARG_STRING, arg_data = 0x560576293f08,
            description = 0x560574d623e0 "Create the initial window with the given geometry.", arg_description = 0x560574d632fb "GEOMETRY"}, {
            long_name = 0x560574d62413 "no-default-window", short_name = 110 'n', flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x7fff79a01e18,
            description = 0x560574d62425 "Only create windows for explicitly specified URIs.", arg_description = 0x0}, {long_name = 0x560574d62458 "no-desktop", short_name = 0 '\000',
            flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x560576293ef8, description = 0x560574d62463 "Do not manage the desktop (ignore the preference set in the preferences dialog).",
            arg_description = 0x0}, {long_name = 0x560574d624b4 "force-desktop", short_name = 0 '\000', flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x560576293efc,
            description = 0x560574d624c2 "Manage the desktop regardless of set preferences or environment (on new startup only)", arg_description = 0x0}, {
            long_name = 0x560574d53872 "tabs", short_name = 116 't', flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x7fff79a01e20, description = 0x560574d62518 "Open URIs in tabs.",
            arg_description = 0x0}, {long_name = 0x560574d55e96 "browser", short_name = 0 '\000', flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x7fff79a01e24,
            description = 0x560574d6252b "Open a browser window.", arg_description = 0x0}, {long_name = 0x560574d54d9a "quit", short_name = 113 'q', flags = 0, arg = G_OPTION_ARG_NONE,
arg_--Type <RET> for more, q to quit, c to continue without paging--            data = 0x7fff79a01e1c, description = 0x560574d62542 "Quit Caja.", arg_description = 0x0}, {long_name = 0x560574d574f1 "select", short_name = 115 's', flags = 0,
            arg = G_OPTION_ARG_NONE, arg_data = 0x7fff79a01e14, description = 0x560574d6254d "Select specified URI in parent folder.", arg_description = 0x0}, {
            long_name = 0x560574d509d8 "", short_name = 0 '\000', flags = 0, arg = G_OPTION_ARG_STRING_ARRAY, arg_data = 0x7fff79a01e40, description = 0x0,
            arg_description = 0x560574d62574 "[URI...]"}, {long_name = 0x0, short_name = 0 '\000', flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x0, description = 0x0,
            arg_description = 0x0}}
        context = 0x560576296500
        error = 0x0
        argc = 1
        argv = 0x56057625b650
        files = <optimized out>
        idx = <optimized out>
        len = <optimized out>
#17 0x00007f719da3553e in g_application_run () from /usr/lib64/libgio-2.0.so.0
No symbol table info available.
#18 0x0000560574c6f183 in main (argc=3, argv=0x7fff79a02388) at /home/tkloczko/rpmbuild/BUILD/caja-1.27.0/src/caja-main.c:271
        retval = <optimized out>
        application = 0x560576294000
(gdb)
quit
```
</details>

#### Steps to reproduce the behaviour
Build and execute "make check"

#### MATE general version
1.27.0

#### Linux Distribution
My own.

**Comment by lukefromdc** [comment]
I just tried this on Debian Unstable w local GKT and glib builds, make check completed without error. Wonder what's different?

**Comment by kloczek** [comment]
Do you have installed caja in this env?  🤔
