### ISSUE TITLE
Caja crashes when making a thumbnail of a gigapixel image

### ISSUE THREAD

**Issue by patrakov** [mate-desktop/caja#393]
To reproduce: put a 32000x32000 solid-color png image in your home folder. Open Caja. It will try to make a thumbnail of this image and crash with SIGSEGV. The backtrace is:

```
(gdb) bt full
#0  scale_line (weights=weights@entry=0x7f02a8279010, n_x=251, n_y=251, dest=dest@entry=0x7f02c001df00 "", dest_x=dest_x@entry=0, 
    dest_end=dest_end@entry=0x7f02c001e07d "", dest_channels=dest_channels@entry=3, dest_has_alpha=dest_has_alpha@entry=0, 
    src=src@entry=0x7f02c000e840, src_channels=src_channels@entry=3, src_has_alpha=src_has_alpha@entry=0, x_init=<optimized out>, 
    x_step=x_step@entry=16384000, src_width=src_width@entry=32000, check_size=check_size@entry=0, color1=color1@entry=0, 
    color2=color2@entry=0)
    at /usr/portage/packages/portage/x11-libs/gdk-pixbuf-2.30.8/work/gdk-pixbuf-2.30.8/gdk-pixbuf/pixops/pixops.c:1011
        ta = <optimized out>
        q = 0x7f016da3ec10 <error: Cannot access memory at address 0x7f016da3ec10>
        line_weights = 0x7f02a8279010
        r = 0
        g = 0
        b = 0
        x_scaled = 0
        pixel_weights = 0x7f02a8279010
        x = 0
        i = 0
        j = 0
#1  0x00007f02ea01b7e9 in pixops_process (dest_buf=<optimized out>, render_x0=0, render_y0=<optimized out>, 
    render_x1=<optimized out>, render_y1=<optimized out>, dest_rowstride=<optimized out>, dest_channels=3, dest_has_alpha=0, 
    src_buf=0x7f01ece4f010 "\231", src_width=32000, src_height=32000, src_rowstride=96000, src_channels=3, src_has_alpha=0, 
    scale_x=<optimized out>, scale_y=<optimized out>, check_x=0, check_y=0, check_size=0, color1=0, color2=0, 
    filter=0x7f02d4c0a9e0, line_func=0x7f02ea019da0 <scale_line>, pixel_func=0x7f02ea01ab30 <scale_pixel>)
    at /usr/portage/packages/portage/x11-libs/gdk-pixbuf-2.30.8/work/gdk-pixbuf-2.30.8/gdk-pixbuf/pixops/pixops.c:1350
        x_start = <optimized out>
        run_weights = 0x7f02a8279010
        new_outbuf = <optimized out>
        tcolor2 = 0
        dest_x = <optimized out>
        y_start = <optimized out>
        tcolor1 = 0
        outbuf = <optimized out>
        outbuf_end = 0x7f02c001e080 ""
        i = 90
        j = <optimized out>
        x = <optimized out>
        y = 1474560000
        line_bufs = 0x7f02c000e840
        x_step = 16384000
        y_step = 16384000
        check_shift = <optimized out>
        scaled_x_offset = 0
        run_end_x = <optimized out>
        run_end_index = <optimized out>
#2  0x00007f02ea01c059 in _pixops_scale_real (interp_type=PIXOPS_INTERP_BILINEAR, interp_type@entry=49200, 
    scale_y=0.0040000000000000001, scale_x=0.0040000000000000001, src_has_alpha=0, src_channels=3, src_rowstride=96000, 
    src_height=32000, src_width=32000, src_buf=0x7f01ece4f010 "\231", dest_has_alpha=0, dest_channels=3, dest_rowstride=384, 
    render_y1=<optimized out>, render_x1=128, render_y0=<optimized out>, render_x0=0, dest_buf=<optimized out>)
    at /usr/portage/packages/portage/x11-libs/gdk-pixbuf-2.30.8/work/gdk-pixbuf-2.30.8/gdk-pixbuf/pixops/pixops.c:2214
        filter = {x = {n = 251, offset = 0, weights = 0x7f02c0021810}, y = {n = 251, offset = 0, weights = 0x7f02c00295a0}, 
          overall_alpha = 1}
        line_func = <optimized out>
#3  _pixops_scale (dest_buf=<optimized out>, dest_width=dest_width@entry=128, dest_height=dest_height@entry=128, 
    dest_rowstride=384, dest_channels=3, dest_has_alpha=0, src_buf=0x7f01ece4f010 "\231", src_width=32000, src_height=32000, 
    src_rowstride=96000, src_channels=3, src_has_alpha=0, dest_x=dest_x@entry=0, dest_y=dest_y@entry=0, 
    dest_region_width=dest_region_width@entry=128, dest_region_height=dest_region_height@entry=128, offset_x=offset_x@entry=0, 
    offset_y=<optimized out>, scale_x=scale_x@entry=0.0040000000000000001, scale_y=scale_y@entry=0.0040000000000000001, 
    interp_type=interp_type@entry=PIXOPS_INTERP_BILINEAR)
    at /usr/portage/packages/portage/x11-libs/gdk-pixbuf-2.30.8/work/gdk-pixbuf-2.30.8/gdk-pixbuf/pixops/pixops.c:2269
        new_dest_buf = <optimized out>
        render_x0 = 0
        render_y0 = <optimized out>
        render_x1 = 128
        render_y1 = <optimized out>
#4  0x00007f02ea013bad in gdk_pixbuf_scale (src=0x11df1e0, dest=0x11df230, dest_x=0, dest_y=0, dest_width=128, dest_height=128, 
    offset_x=0, offset_y=<optimized out>, scale_x=0.0040000000000000001, scale_y=0.0040000000000000001, 
    interp_type=GDK_INTERP_BILINEAR)
    at /usr/portage/packages/portage/x11-libs/gdk-pixbuf-2.30.8/work/gdk-pixbuf-2.30.8/gdk-pixbuf/gdk-pixbuf-scale.c:147
        __func__ = "gdk_pixbuf_scale"
#5  0x00007f02ea0141fa in gdk_pixbuf_scale_simple (src=src@entry=0x11df1e0, dest_width=128, dest_height=dest_height@entry=128, 
    interp_type=interp_type@entry=GDK_INTERP_BILINEAR)
    at /usr/portage/packages/portage/x11-libs/gdk-pixbuf-2.30.8/work/gdk-pixbuf-2.30.8/gdk-pixbuf/gdk-pixbuf-scale.c:321
        dest = 0x11df230
        __func__ = "gdk_pixbuf_scale_simple"
#6  0x00007f02ea0154e0 in get_scaled_pixbuf (scaled=0xfff8c0, pixbuf=0x11df1e0)
    at /usr/portage/packages/portage/x11-libs/gdk-pixbuf-2.30.8/work/gdk-pixbuf-2.30.8/gdk-pixbuf/gdk-pixbuf-scaled-anim.c:138
        quark = 1434
        options = 0x0
#7  0x00007f02eb9f5b70 in ?? () from /usr/lib64/libmate-desktop-2.so.17
No symbol table info available.
#8  0x00007f02eb9f6042 in mate_desktop_thumbnail_factory_generate_thumbnail () from /usr/lib64/libmate-desktop-2.so.17
No symbol table info available.
#9  0x0000000000513f21 in ?? ()
No symbol table info available.
#10 0x00007f02e86ee3a4 in start_thread () from /lib64/libpthread.so.0
---Type <return> to continue, or q <return> to quit---
No symbol table info available.
#11 0x00007f02e843586d in clone () from /lib64/libc.so.6
```

This is different from bug #279, because my backtrace has gdk-pixbuf at the innermost frame, while that backtrace has something freetype-related.

**Comment by monsta** [comment]
Looks like upstream bug in gdk-pixbuf

**Comment by monsta** [comment]
Can you test it with 1.16? It might be fixed in https://github.com/mate-desktop/caja/commit/2d8ba15b3905be710036bb729b7acaa7e8e62814.

**Comment by monsta** [comment]
Closing - it's an issue in gdk-pixbuf, same as https://github.com/mate-desktop/caja/issues/641.
