### ISSUE TITLE
Caja crash on ctrl-scroll

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/caja#516]
I found out by accident while trying to test scrollwheel workspace switchng that holding down the CTRL key while using the scroll wheel will crash caja if caja is focussed. This could do things like crash a user's file copy job from a failed attempt to scroll anything that actually uses this combination. Got this error in terminal:

`ERROR:fm-directory-view.c:10910:fm_directory_view_handle_scroll_event: code should not be reached`

**Comment by monsta** [comment]
Hmm, this combination just changes zoom level in GTK+2 build...

**Comment by monsta** [comment]
Oops... GTK+3 build indeed crashes :open_mouth: 

```
(gdb) bt full
#0  0x00007fc9bc184507 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
        resultvar = 0
        pid = 1023
        selftid = 1023
#1  0x00007fc9bc1858da in __GI_abort () at abort.c:89
        save_stage = 2
        act = 
          {__sigaction_handler = {sa_handler = 0x2748f90, sa_sigaction = 0x2748f90}, sa_mask = {__val = {98, 140504444465888, 140504505384672, 140720651358432, 72057594037927936, 16777216, 6989586621679009792, 140501265154048, 5660047, 41193360, 140504424446976, 0, 0, 41193216, 140504424447024, 140504424446976}}, sa_flags = -1, sa_restorer = 0x2748f90}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007fc9bd568b75 in g_assertion_message (domain=domain@entry=0x0, file=file@entry=0x565d8f "fm-directory-view.c", line=line@entry=10910, func=func@entry=0x567020 <__func__.60682> "fm_directory_view_handle_scroll_event", message=message@entry=0x2738160 "code should not be reached")
    at /build/glib2.0-2.46.2/./glib/gtestutils.c:2429
        lstr = "10910\000\000\000\356\270\034\274\311\177\000\000\000\000\000\000\000\000\000\000\033\000\000\000\000\000\000"
        s = 0x2748f90 ""
#3  0x00007fc9bd568c0a in g_assertion_message_expr (domain=domain@entry=0x0, file=file@entry=0x565d8f "fm-directory-view.c", line=line@entry=10910, func=func@entry=0x567020 <__func__.60682> "fm_directory_view_handle_scroll_event", expr=expr@entry=0x0) at /build/glib2.0-2.46.2/./glib/gtestutils.c:2444
        s = 0x2738160 "code should not be reached"
#4  0x000000000049f4fd in fm_directory_view_handle_scroll_event (directory_view=<optimized out>, event=<optimized out>) at fm-directory-view.c:10910
        directory_view = <optimized out>
        event = <optimized out>
#5  0x000000000049f557 in fm_directory_view_scroll_event (widget=0x2740260 [FMIconView], event=0x2c1c330) at fm-directory-view.c:10925
        directory_view = <optimized out>
#6  0x00007fc9bf07ab3a in _gtk_marshal_BOOLEAN__BOXEDv (closure=0x1ed7da0, return_value=0x7ffc146fd3c0, instance=<optimized out>, args=<optimized out>, marshal_data=<optimized out>, n_params=<optimized out>, param_types=0x1ed7dd0) at /build/gtk+3.0-BhvX6v/gtk+3.0-3.18.7/./gtk/gtkmarshalers.c:131
        cc = <optimized out>
        data1 = <optimized out>
        data2 = <optimized out>
        callback = <optimized out>
        arg0 = 0x2c1c330
Python Exception <class 'gdb.error'> Attempt to dereference a generic pointer.: 
#7  0x00007fc9bd818174 in _g_closure_invoke_va (closure=closure@entry=0x1ed7da0, return_value=return_value@entry=0x7ffc146fd3c0, instance=instance@entry=0x2740260, args=args@entry=0x7ffc146fd490, n_params=<optimized out>, param_types=0x1ed7dd0) at /build/glib2.0-2.46.2/./gobject/gclosure.c:864
        marshal = <optimized out>
        marshal_data = <optimized out>
        in_marshal = 0
        real_closure = 0x1ed7d80
        __func__ = "_g_closure_invoke_va"
#8  0x00007fc9bd832488 in g_signal_emit_valist (instance=0x2740260, signal_id=<optimized out>, detail=0, var_args=var_args@entry=0x7ffc146fd490)
    at /build/glib2.0-2.46.2/./gobject/gsignal.c:3292
        return_accu = <optimized out>
        accu = 
              {g_type = 20, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        accumulator = 0x1ed7e60
        emission = 
          {next = 0x0, instance = 0x2740260, ihint = {signal_id = 52, detail = 0, run_type = G_SIGNAL_RUN_LAST}, state = EMISSION_RUN, chain_type = 37811152}
        signal_id = 52
        instance_type = <optimized out>
        emission_return = 
              {g_type = 20, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
---Type <return> to continue, or q <return> to quit---
        rtype = 20
        static_scope = 0
        fastpath_handler = <optimized out>
        closure = <optimized out>
        run_type = <optimized out>
        l = <optimized out>
        fastpath = <optimized out>
        instance_and_params = <optimized out>
        signal_return_type = <optimized out>
        param_values = <optimized out>
        i = <optimized out>
        n_params = <optimized out>
        __func__ = "g_signal_emit_valist"
#9  0x00007fc9bd83305f in g_signal_emit (instance=instance@entry=0x2740260, signal_id=<optimized out>, detail=detail@entry=0)
    at /build/glib2.0-2.46.2/./gobject/gsignal.c:3439
Python Exception <class 'gdb.error'> Attempt to dereference a generic pointer.: 
#10 0x00007fc9bf1b7efc in gtk_widget_event_internal (widget=0x2740260 [FMIconView], event=0x2c1c330)
    at /build/gtk+3.0-BhvX6v/gtk+3.0-3.18.7/./gtk/gtkwidget.c:7692
        signal_num = <optimized out>
        return_val = 0
        handled = 0
        event = 0x2c1c330
        widget = 0x2740260 [FMIconView]
#11 0x00007fc9bf077e5e in propagate_event (topmost=<optimized out>, event=<optimized out>, widget=0x2740260 [FMIconView])
    at /build/gtk+3.0-BhvX6v/gtk+3.0-3.18.7/./gtk/gtkmain.c:2527
        tmp = <optimized out>
        handled_event = <optimized out>
        handled_event = 0
#12 0x00007fc9bf077e5e in propagate_event (widget=<optimized out>, event=0x2c1c330, captured=<optimized out>, topmost=0x0)
    at /build/gtk+3.0-BhvX6v/gtk+3.0-3.18.7/./gtk/gtkmain.c:2629
        handled_event = 0
#13 0x00007fc9bf079c5c in gtk_main_do_event (event=0x2c1c330) at /build/gtk+3.0-BhvX6v/gtk+3.0-3.18.7/./gtk/gtkmain.c:1850
        event_widget = <optimized out>
        grab_widget = 0x2130b80 [FMIconContainer]
        topmost_widget = <optimized out>
        window_group = 0x24cc420 [GtkWindowGroup]
        rewritten_event = <optimized out>
        device = 0x1ec4a50 [GdkX11DeviceXI2]
        tmp_list = <optimized out>
        __func__ = "gtk_main_do_event"
#14 0x00007fc9bebf2d42 in gdk_event_source_dispatch (source=<optimized out>, callback=<optimized out>, user_data=<optimized out>)
    at /build/gtk+3.0-BhvX6v/gtk+3.0-3.18.7/./gdk/x11/gdkeventsource.c:364
        display = <optimized out>
        event = <optimized out>
#15 0x00007fc9bd542fd7 in g_main_context_dispatch (context=0x1edea30) at /build/glib2.0-2.46.2/./glib/gmain.c:3154
        dispatch = 0x7fc9bebf2d20 <gdk_event_source_dispatch>
        prev_source = 0x0
        was_in_call = 0
        user_data = 0x0
        callback = 0x0
        cb_funcs = <optimized out>
        cb_data = <optimized out>
        need_destroy = <optimized out>
---Type <return> to continue, or q <return> to quit---
        source = 0x1ede960
        current = 0x1f23b80
        i = 0
#16 0x00007fc9bd542fd7 in g_main_context_dispatch (context=context@entry=0x1edea30) at /build/glib2.0-2.46.2/./glib/gmain.c:3769
#17 0x00007fc9bd543230 in g_main_context_iterate (context=0x1edea30, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at /build/glib2.0-2.46.2/./glib/gmain.c:3840
        max_priority = 2147483647
        timeout = 92
        some_ready = 1
        nfds = <optimized out>
        allocated_nfds = 5
        fds = 0x1f2cf20
#18 0x00007fc9bd543552 in g_main_loop_run (loop=0x24026c0) at /build/glib2.0-2.46.2/./glib/gmain.c:4034
        __func__ = "g_main_loop_run"
#19 0x00007fc9bf078e35 in gtk_main () at /build/gtk+3.0-BhvX6v/gtk+3.0-3.18.7/./gtk/gtkmain.c:1241
        loop = 0x24026c0
#20 0x000000000044ae41 in main (argc=1, argv=0x7ffc146fdb88) at caja-main.c:640
        kill_shell = 0
        no_default_window = 1
        browser_window = 0
        no_desktop = 0
        version = 0
        autostart_mode = <optimized out>
        autostart_id = <optimized out>
        geometry = 0x0
        remaining = 0x0
        perform_self_check = 0
        application = 0x1f2a000 [CajaApplication]
        context = <optimized out>
        file = <optimized out>
        fileinfo = <optimized out>
        appinfo = <optimized out>
        uri = <optimized out>
        uris = 0x0
        uris_array = <optimized out>
        error = 0x0
        i = <optimized out>
        options = 
            {{long_name = 0x55a404 "check", short_name = 99 'c', flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x7ffc146fd7f4, description = 0x55a468 "Perform a quick set of self-check tests.", arg_description = 0x0}, {long_name = 0x579635 "version", short_name = 0 '\000', flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x7ffc146fd7f0, description = 0x55a498 "Show the version of the program.", arg_description = 0x0}, {long_name = 0x55e511 "geometry", short_name = 103 'g', flags = 0, arg = G_OPTION_ARG_STRING, arg_data = 0x7ffc146fd7f8, description = 0x55a4c0 "Create the initial window with the given geometry.", arg_description = 0x56645b "GEOMETRY"}, {long_name = 0x55a362 "no-default-window", short_name = 110 'n', flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x7ffc146fd7e4, description = 0x55a4f8 "Only create windows for explicitly specified URIs.", arg_description = 0x0}, {long_name = 0x55a374 "no-desktop", short_name = 0 '\000', flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x7ffc146fd7ec, description = 0x55a530 "Do not manage the desktop (ignore the preference set in the preferences dialog).", arg_description = 0x0}, {long_name = 0x55bb57 "browser", short_name = 0 '\000', flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x7ffc146fd7e8, description = 0x55a37f "open a browser window.", arg_description = 0x0}, {long_name = 0x57bedd "quit", short_name = 113 'q', flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x7ffc146fd7e0, description = 0x55a396 "Quit Caja.", arg_description = 0x0}, {long_name = 0x55fb2d "", short_name = 0 '\000', flags = 0, arg = G_OPTION_ARG_STRING_ARRAY, arg_data = 0x7ffc146fd800, description = 0x0, arg_description = 0x55a3a1 "[URI...]"}, {long_name = 0x0, short_name = 0 '\000', flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x0, description = 0x0, arg_description = 0x0}}
(gdb) 

```

**Comment by lukefromdc** [comment]
Just built this, ctrl-scroll now changes the zoom level in a navigation window as intended. No effect on desktop, presumably also as intended

**Comment by monsta** [comment]
Yes, there's no zooming on desktop here as well. I think it's the intended behavior for desktop.
