### ISSUE TITLE
caja segfault due to uninitialized variable

### ISSUE THREAD

**Issue by rnagy** [mate-desktop/caja#747]
Caja crashed due to the uninitialized geometry variable in caja_application_open(),
if there is no geometry specified on the command line:

```
Core was generated by 'caja'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00001da950b04398 in XParseGeometry () from /usr/X11R6/lib/libX11.so.16.1
[Current thread is 1 (process 397413)]
(gdb) bt
#0  0x00001da950b04398 in XParseGeometry () from /usr/X11R6/lib/libX11.so.16.1
#1  0x00001da706594175 in eel_gdk_parse_geometry (string=<optimized out>, x_return=<optimized out>, y_return=<optimized out>, width_return=<optimized out>, 
    height_return=<optimized out>) at eel-gdk-extensions.c:460
#2  0x00001da70659c04d in eel_gtk_window_set_initial_geometry_from_string (window=0x1da94c3fc3c0, 
    geometry_string=0x1 <error: Cannot access memory at address 0x1>, minimum_width=300, minimum_height=100, ignore_position=0) at eel-gtk-extensions.c:244
#3  0x00001da70650a958 in open_window (application=0x1da9a8f68150, location=0x1da98a68f4a0, screen=0x1da94d58a0b0, 
    geometry=0x1 <error: Cannot access memory at address 0x1>, browser_window=<optimized out>) at caja-application.c:281
#4  0x00001da70650aa2d in caja_application_open (app=<optimized out>, files=0x1da91b489020, n_files=<optimized out>, options=<optimized out>)
    at caja-application.c:349
#5  0x00001da957b317c4 in ffi_call_unix64 () from /usr/local/lib/libffi.so.1.2
#6  0x00001da957b315d1 in ffi_call () from /usr/local/lib/libffi.so.1.2
#7  0x00001da97d83d7b6 in g_cclosure_marshal_generic_va () from /usr/local/lib/libgobject-2.0.so.4200.4
#8  0x00001da97d83f3ed in _g_closure_invoke_va () from /usr/local/lib/libgobject-2.0.so.4200.4
#9  0x00001da97d857846 in g_signal_emit_valist () from /usr/local/lib/libgobject-2.0.so.4200.4
#10 0x00001da97d858a41 in g_signal_emit () from /usr/local/lib/libgobject-2.0.so.4200.4
#11 0x00001da706509b2c in caja_application_local_command_line (application=0x1da9a8f68150, arguments=0x7f7ffffec3d0, exit_status=<optimized out>)
    at caja-application.c:2190
#12 0x00001da941ee2031 in g_application_run () from /usr/local/lib/libgio-2.0.so.4200.4
#13 0x00001da70651ce56 in main (argc=1, argv=0x7f7ffffec4b8) at caja-main.c:295
```

The fix:

```
--- src/caja-application.c.orig Fri Mar 17 19:18:34 2017
+++ src/caja-application.c      Fri Mar 17 19:18:38 2017
@@ -319,7 +319,7 @@ caja_application_open (GApplication *app,
 {
     CajaApplication *self = CAJA_APPLICATION (app);
     gboolean browser_window = FALSE;
-    const gchar *geometry;
+    const gchar *geometry = NULL;
     const char splitter = '=';
 
     g_debug ("Open called on the GApplication instance; %d files", n_files);
```

**Comment by lukefromdc** [comment]
While this never segfaulted on any of my systems, differences in compilers or libraries could explain that-and in any case an uninitialized variable is an error. Thanks for catching this. I never got a compiler warning about this nor a runtime warning.
