### ISSUE TITLE
Caja freezes/hangs sometimes when browsing a network share(samba)

### ISSUE THREAD

**Issue by aldorgan** [mate-desktop/caja#800]
#### Expected behaviour
Browse a network share with no freezes/hangs

#### Actual behaviour
sometimes i can browse a network share without problems, but other times when i go in to a folder on the share, caja freezes/hangs and i need to force quit caja and restart it to start browsing again on the share. i have tried nautilus and that is working fine, no hangs or freezes.

#### Steps to reproduce the behaviour
Open caja and it hangs, close it, open it again and it hangs after a while.

#### MATE general version
1.16 

#### Package version
1.16.6

#### Linux Distribution
Debian 9

**Comment by raveit65** [comment]
Samba shares are part of https://github.com/mate-desktop/caja-extensions

**Comment by monsta** [comment]
This is about browsing already created samba shares, so it's about Caja.
Might be the same as https://github.com/mate-desktop/caja/issues/380, or related to it.

**Comment by underr-ua** [comment]
I have a similar problem, but in my case Caja freeze when i press "go to previous visited..." or "open the parent folder" in samba shares. After that i find one zombie process - _cat_

**Comment by pfeerick** [comment]
I can confirm this issue still appears to be still an active issue with Caja 1.18.4 on Ubuntu Mate 17.10. It is most frequently triggered in my case by clicking on the breadcrumb bar, and going back to the root of the samba share, or indeed any folder higher up the hierarchy than the current folder, or by going back to the previous level.

**Comment by itcrowd72** [comment]
Same problem. Caja is unusable with shares

**Comment by lukefromdc** [comment]
My experience is that ANY slow filesystem can freeze the rest of Caja, not sure if Nautilus or Nemo ever fixed this either

**Comment by phocean** [comment]
This issue should be reopened, because it happens quite often to me.
Caja would hang forever while browsing a gvfs mounted directory (mouse cursor in waiting state).
And this is not due to a bad or slow network connection, it is rather good.

It never happens with Nemo or Nautilus (except that this one crashes sometimes), although I often test and use these.

**Comment by jondo** [comment]
I currently see it with Linux Mint 19.1 (with Caja 1.20.2).
@aldorgan, According to @monsta in https://github.com/mate-desktop/caja-extensions/issues/34, this is not an extensions issue, so maybe you should reopen it here?

**Comment by jondo** [comment]
In my case, the involved Samba server is Debian 8 "jessie" with Samba `4.2.14+dfsg-0+deb8u9`  (4.2.14 + Debian-backported patches). I plan to additionally test against a newer Samba version.

**Comment by dianaxxyyzz** [comment]
My caja did not saw windows 10  shares , and when it saw them with some random configs I tried it freeze on "go back" .

My last config file that worked for smb.conf is this . I also had to enable in windows 10 to use smb1 samba protocol . Now I no longer have the "go back" freeze bug .

`[global]

workgroup = WORKGROUP

server string = Samba Server %v

netbios name = ubuntu

name resolve order = bcast

dns proxy = no

interfaces = 192.168.200.0/24

bind interfaces only = yes

ntlm auth = true

security = user

map to guest = Bad User

client max protocol = NT1

[Public]
   path = /samba/public
   browsable =yes
   writable = yes
   guest ok = yes
   read only = no
   public = yes`

**Comment by Jorilx** [comment]
For the record it happens with Caja 1.20.3 on Debian 10, too

**Comment by lukefromdc** [comment]
ALWAYS all of the Nautilus-based file browsers (unless Nautilus or Nemo recently found a fix) have had trouble coping with a slow or nonresponsive remote filesystem. Could be a GVFS issue, but waiting on GVFS or waiting on the remote filesystem itself both seem to be things we could limit on this end. The waiting window ideally would be the only window shown "loading" its content while others remained responsive. Browsers have managed to do this in a single process in the past,should be possible here to.

What I do NOT know is how much code would have to change to keep all other windows responsive.  Caja would have to jump out of the waiting task (the window w slow content) at intervals, update all other windows, and jump back to the waiting task. Caja is kept one process by using GtkApplication, this makes it easier to among other things save open windows.

**Comment by Jorilx** [comment]
Sadly I still haven't found a way to reproduce this bug consistently, but what I've observed is that **when** it happens, it happens when I use the "open parent" button (or press backspace on the keyboard)

I was wondering, in case I somehow manage to trigger the bug, what could I try to help debug the problem?

(Thanks for reopening this issue!)

**Comment by Jorilx** [comment]
I have just learned of [gcore](https://man7.org/linux/man-pages/man1/gcore.1.html), it looks like it can generate a core dump of a running program. Would that be useful?

**Comment by lukefromdc** [comment]
I don't know enough about that to make use of it(or thus to answer), though someone else here might.

**Comment by Jorilx** [comment]
For the record, I've backported Caja 1.24.0 to Debian 10 but the problem is still there.
I've managed to get a core dump with gcore though! Tomorrow I'll try to see if I can understand something about it :grin:

**Comment by Jorilx** [comment]
Here's the backtrace:
```
(gdb) bt
#0  0x00007f678bee6af9 in syscall () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f678c7487bc in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f678c92132b in g_dbus_connection_signal_subscribe () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#3  0x00007f678c92b762 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007f678c92bab8 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#5  0x00007f678c870183 in g_async_initable_new_valist_async () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#6  0x00007f678c870238 in g_async_initable_new_async () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#7  0x00007f6787c95458 in gvfs_dbus_daemon_proxy_new (connection=0x55e25cd41500, flags=flags@entry=G_DBUS_PROXY_FLAGS_NONE, name=name@entry=0x0, object_path=object_path@entry=0x7f6787ce8b35 "/org/gtk/vfs/Daemon", cancellable=cancellable@entry=0x0, callback=callback@entry=0x7f6787cddcd0 <cancelled_got_proxy>, 
    user_data=0x28a) at common/gvfsdbus.c:1202
#8  0x00007f6787cdda78 in async_call_cancelled_cb (cancellable=<optimized out>, _data=<optimized out>) at ../client/gvfsdaemondbus.c:376
#9  0x00007f678c7e0c9d in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#10 0x00007f678c7f4375 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007f678c7fd2fe in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007f678c7fd9bf in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007f678c8742f8 in g_cancellable_cancel () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#14 0x000055e25c2ab32d in file_info_cancel (directory=directory@entry=0x55e25ced84f0) at caja-directory-async.c:613
#15 0x000055e25c2abb40 in file_info_stop (directory=directory@entry=0x55e25ced84f0) at caja-directory-async.c:3762
#16 0x000055e25c2ac258 in start_or_stop_io (directory=0x55e25ced84f0) at caja-directory-async.c:4963
#17 caja_directory_async_state_changed (directory=<optimized out>) at caja-directory-async.c:5054
#18 caja_directory_async_state_changed (directory=<optimized out>) at caja-directory-async.c:5034
#19 0x000055e25c2adcd8 in dequeue_pending_idle_callback (callback_data=callback_data@entry=0x55e25ced84f0) at caja-directory-async.c:1078
#20 0x000055e25c2af224 in directory_load_done (directory=directory@entry=0x55e25ced84f0, error=<optimized out>) at caja-directory-async.c:1203
#21 0x000055e25c2af454 in more_files_callback (source_object=<optimized out>, res=0x55e25d756430, user_data=0x55e25d8ef720) at caja-directory-async.c:2227
#22 0x00007f678c88d626 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#23 0x00007f678c8c97a9 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#24 0x00007f678c8ca226 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#25 0x00007f6787cd4b0f in _g_task_return_pointer_idle_cb (task=0x55e25d756430) at ../client/gdaemonfileenumerator.c:386
#26 0x00007f678c6fee98 in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#27 0x00007f678c6ff288 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x00007f678c6ff31c in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x00007f678c8f4a3d in g_application_run () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#30 0x000055e25c222318 in main (argc=1, argv=0x7ffdf22c2378) at caja-main.c:271
```
Sadly I can't find the dbgsym packages for Debian 10 security updates :/
